### ISSUE TITLE
German package is broken

### ISSUE THREAD

**Issue by magdesign** [apertium/apertium-deu#1]
However I install the German language, with apertium-get or compiling from this repo, as single or language pairs...

the german language always errors:

```
/dev/fd/63: line 1: lsx-proc: command not found
/dev/fd/63: line 1: lsx-proc: command not found
````
(all other languages do work)

How can this be fixed?

Thanks for any help...

**Comment by mr-martian** [comment]
That indicates that `apertium-separable` is not installed. How did you install the Apertium core tools?

**Comment by magdesign** [comment]
Thanks for your response.
I installed each package with compiling from git. 
So german needs `apertium-separable` and the others not... ? 
just on it to search and compile...

**Comment by magdesign** [comment]
wow. thank you so much! 😘

installing [apertium-separable ](https://github.com/apertium/apertium-separable) fixed the issue.

btw.
seriously thinking of packing this for postmarketOS/Alpine Linux, since i was able to build a translator with speech feedback for my linuxmobile phone.

**Comment by mr-martian** [comment]
What translation pair was this failing in? It's actually an issue with the dependency list there.

**Comment by magdesign** [comment]
apertium-deu	

apertium-eng-deu 

and i can not:
`./apertium-get.sh fin-deu`

it sucks the package and when i go into 
and want to configure:

```
checking for zcat... /bin/zcat
checking for mteval-v13a.pl... false
checking for wrap-xml.prompsit-version.sh... false
checking for saxon9-transform... no
configure: error: AP_CHECK_LING not defined, is apertium.m4 in ACLOCAL_PATH? See: https://wiki.apertium.org/wiki/Installation_troubleshooting
```

tbh. i dont get why some languages install in one go and others dont.

**Comment by mr-martian** [comment]
Ok, eng-deu uses apertium-separable but previously didn't depend on it properly. Afaict fin-deu does not use it. For the last error message you posted, see the wiki page in the error description.
